apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hasher
  name: hasher
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hasher
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hasher
    spec:
      containers:
      - image: dockercoins/hasher:v0.1
        name: hasher
        resources: {}
status: {}
